#!/bin/bash
# Generate .claude-plugin/lib/cpf-known-upstream.json: the sha256 of each
# version cpf has ever shipped (every v* release tag plus the working tree)
# for every overwrite-tier path -- including versions shipped at the
# path's older location (upgrade-tiers.json relocations) -- and for every
# file under a migration's reorg_paths (files that moved into the plugin).
#
# cpf-managed-file.sh uses this list when a host has no cached baseline
# (.cpf/upstream-cache/<path>): a host file that matches a released
# version was never edited and can be upgraded without prompting.
#
#   scripts/gen-known-upstream.sh           # write the file
#   scripts/gen-known-upstream.sh --check   # exit 1 if it is out of date
#
# Requires the release tags locally (git fetch --tags).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
TIERS=".claude-plugin/upgrade-tiers.json"
OUT=".claude-plugin/lib/cpf-known-upstream.json"
SCAFFOLD_DIRS=(common github gitlab jenkins)

sha256_stdin() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | cut -d' ' -f1
    else
        shasum -a 256 | cut -d' ' -f1
    fi
}

TAGS=()
while IFS= read -r t; do
    TAGS+=("$t")
done < <(git tag -l 'v*' --sort=version:refname)
if [[ "${#TAGS[@]}" -eq 0 ]]; then
    echo "gen-known-upstream: no v* tags found (run git fetch --tags)" >&2
    exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

while IFS= read -r path; do
    legacy="$(jq -r --arg p "$path" '.relocations[$p] // empty' "$TIERS")"
    candidates=("$path")
    [[ -n "$legacy" ]] && candidates+=("$legacy")
    for cand in "${candidates[@]}"; do
        for dir in "${SCAFFOLD_DIRS[@]}"; do
            src=".claude-plugin/scaffold/$dir/$cand"
            for t in "${TAGS[@]}"; do
                if git cat-file -e "$t:$src" 2>/dev/null; then
                    printf '%s\t%s\n' "$path" "$(git show "$t:$src" | sha256_stdin)" >>"$tmp"
                fi
            done
            if [[ -f "$src" ]]; then
                printf '%s\t%s\n' "$path" "$(sha256_stdin <"$src")" >>"$tmp"
            fi
        done
    done
done < <(jq -r '.tiers.overwrite[]' "$TIERS")

# Files that moved into the plugin (migration reorg_paths such as
# prompts/ or .specify/WORKFLOW.md): the migration guide uses these hashes
# to tell a project's untouched copy from a customized one.
while IFS= read -r reorg; do
    for t in "${TAGS[@]}" WORKTREE; do
        if [[ "$t" == WORKTREE ]]; then
            # Tracked files only: untracked local files (editor or tool
            # droppings) must not change the output, or CI disagrees.
            list="$(git ls-files -- ".claude-plugin/scaffold/common/${reorg%/}" \
                | sed 's|^\.claude-plugin/scaffold/common/||')"
        else
            list="$(git ls-tree -r --name-only "$t" -- ".claude-plugin/scaffold/common/${reorg%/}" 2>/dev/null \
                | sed 's|^\.claude-plugin/scaffold/common/||')"
        fi
        while IFS= read -r rel; do
            [[ -z "$rel" ]] && continue
            src=".claude-plugin/scaffold/common/$rel"
            if [[ "$t" == WORKTREE ]]; then
                printf '%s\t%s\n' "$rel" "$(sha256_stdin <"$src")" >>"$tmp"
            else
                printf '%s\t%s\n' "$rel" "$(git show "$t:$src" | sha256_stdin)" >>"$tmp"
            fi
        done <<<"$list"
    done
done < <(jq -r '.migrations[]?.reorg_paths[]?' "$TIERS" | sort -u)

json="$(sort -u "$tmp" | jq -R -s '
    split("\n") | map(select(length > 0) | split("\t"))
    | reduce .[] as $r ({}; .[$r[0]] += [$r[1]])
    | {"_comment": "Generated by scripts/gen-known-upstream.sh. sha256 of every released version of each overwrite-tier file (including its relocated older path). Do not edit by hand."} + .
')"

if [[ "${1:-}" == "--check" ]]; then
    if [[ "$(jq -S . <<<"$json")" == "$(jq -S . "$OUT" 2>/dev/null)" ]]; then
        echo "known-upstream: up to date"
        exit 0
    fi
    echo "known-upstream: $OUT is out of date; run scripts/gen-known-upstream.sh" >&2
    exit 1
fi

printf '%s\n' "$json" >"$OUT"
echo "wrote $OUT ($(jq '[to_entries[] | select(.key != "_comment") | .value | length] | add' "$OUT") hashes)"
